config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: "registrations", omniauth_callbacks: 'users/omniauth_callbacks'}

  #########################
  ####
  # Public routes
  ####
  #########################

  root 'public#index'

  get '/articles', to: 'public#articles', as: 'articles'
  get '/news', to: 'public#news', as: 'news'

  get '/photo_albums', to: 'public#photo_albums', as: 'photo_albums'
  get '/video_albums', to: 'public#video_albums', as: 'video_albums'
  get '/album/:id', to: 'public#album', as: 'album'

  get '/finish_registration', to: 'public#finish_registration', as: 'finish_registration'
  # put '/complite_sign_up/:id', to: 'public#complite_sign_up', as: 'complite_sign_up'
  patch '/complite_sign_up/:id', to: 'public#complite_sign_up', as: 'complite_sign_up'

  ###
  # Static pages
  ###

  get '/marriage', to: 'public#marriage', as: 'marriage'
  get '/slav-bazar', to: 'public#slavBazar', as: 'slav-bazar'
  get '/krasnaya-gorka', to: 'public#krasnayaGorka', as: 'krasnaya_gorka'
  get '/rody', to: 'public#rody', as: 'rody'
  get '/vsem_mirom', to: 'public#support', as: 'support'

  #########################
  ####
  # Admin routes
  ####
  #########################

  resources :videos, except: [:index, :show, :new, :edit]
  get 'admin', to: 'admin#dashboard', as: 'admin'
  namespace :admin do
    resources :articles
    resources :users
    resources :video_albums
    resources :photo_albums
    resources :masters
    resources :members
  end

  ###
  # API
  ###

  get '/videoInfo', to: 'videos#getVideoInfo', as: 'getVideoInfo'
  get 'api/get_image_info', to: 'api#get_image_info'
  post 'api/upload_image', to: 'api#upload_image'
  put 'api/change_order', to: 'api#change_order'
  put 'api/change_archive', to: 'api#change_archive', as: 'change_archive'
  put 'api/archive_image', to: 'api#archive_image'
  put 'api/main_image', to: 'api#main_image', as: 'main_image'
  put 'api/bg_image', to: 'api#bg_image', as: 'bg_image'
  put 'api/change_image_info', to: 'api#change_image_info', as: 'change_image_info'
  delete 'api/delete_image', to: 'api#delete_image', as: 'delete_image'
  put 'api/add_member', to: 'api#add_member'
  put 'api/change_payment_method', to: 'api#change_payment_method'
  put 'api/create_payment', to: 'api#create_payment'

  get '/robots.txt' => 'application#robots'
  get 'sitemap.xml', :to => 'sitemap#index', :defaults => { :format => 'xml' }

  ###
  # Posts
  ###

  get '/:id', to: 'public#post', as: 'post'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin/video_album.rb
class Admin::VideoAlbum
  include Mongoid::Document
  include Mongoid::Slug
  include Mongoid::Timestamps
  field :title, type: String
  field :desc, type: String
  field :views, type: Integer
  field :archive, type: Boolean, default: false
  mount_uploader :main_image, ImageUploader

  belongs_to :author, class_name: "User", optional: true
  has_many :videos, class_name: "Video", :dependent => :destroy

  slug :title
end

app/controllers/admin/video_albums_controller.rb
class Admin::VideoAlbumsController < AdminController
  before_action :set_admin_video_album, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /admin/video_albums
  # GET /admin/video_albums.json
  def index
    @admin_video_albums = Admin::VideoAlbum.all
  end

  # GET /admin/video_albums/1
  # GET /admin/video_albums/1.json
  def show
  end

  # GET /admin/video_albums/new
  def new
    @admin_video_album = Admin::VideoAlbum.new
  end

  # GET /admin/video_albums/1/edit
  def edit
    @videos = @admin_video_album.videos.order_by(:order => 'asc')
    @new_video = Video.new
  end

  # POST /admin/video_albums
  # POST /admin/video_albums.json
  def create
    @admin_video_album = Admin::VideoAlbum.new(resource_params)

    respond_to do |format|
      if @admin_video_album.save
        format.html { redirect_to @admin_video_album, notice: 'Video album was successfully created.' }
        format.json { render :show, status: :created, location: @admin_video_album }
      else
        format.html { render :new }
        format.json { render json: @admin_video_album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/video_albums/1
  # PATCH/PUT /admin/video_albums/1.json
  def update
    respond_to do |format|
      if @admin_video_album.update(resource_params)
        format.html { redirect_to @admin_video_album, notice: 'Video album was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_video_album }
      else
        format.html { render :edit }
        format.json { render json: @admin_video_album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/video_albums/1
  # DELETE /admin/video_albums/1.json
  def destroy
    @admin_video_album.destroy
    respond_to do |format|
      format.html { redirect_to admin_video_albums_url, notice: 'Video album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_video_album
      @admin_video_album = Admin::VideoAlbum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resource_params
      params.require(:admin_video_album).permit(:title, :desc, :views, :main_image, :author_id)
    end
end

app/helpers/admin/video_albums_helper.rb
module Admin::VideoAlbumsHelper
end

app/views/admin/video_albums/_form.html.haml
= form_for @admin_video_album do |f|
  - if @admin_video_album.errors.any?
    #error_explanation
      %h2= "#{pluralize(@admin_video_album.errors.count, "error")} prohibited this admin_video_album from being saved:"
      %ul
        - @admin_video_album.errors.full_messages.each do |message|
          %li= message

  = f.hidden_field :author_id, value: current_user.id
  .field.form-group
    = f.label 'Название'
    = f.text_field :title, class: 'form-control'
  .field.form-group
    = f.label 'Главное изображение'
    = f.file_field :main_image, class: 'form-control'
  .field.form-group
    = f.label 'Описание'
    = f.text_area :desc, class: 'form-control', rows: 3
  .field.form-group
    = f.label 'Просмотров'
    = f.number_field :views, class: 'form-control'
  .actions.form-group
    = f.submit 'Сохранить', class: 'btn btn-primary'

app/views/admin/video_albums/edit.html.haml
%h1 Редактирование видеоальбома

= render 'form'

.row.mb-2
  .col-12.video.d-flex.align-items-center.justify-content-center#newVideo{"data-toggle": "modal", "data-target": "#addVideoModal"}
    %div.text-center.my-3
      %p.h2.mt-0
        %b +
      %p.h2.m-0 Новое видео
.row#videosList
  = render @videos

app/views/admin/video_albums/index.html.haml
%h1 Видеоальбомы

= link_to 'Создать видеоальбом', new_admin_video_album_path
%table.table.table-responsive
  %thead
    %tr
      %th Название
      %th Кол-во видео
      %th Просмотров
      %th
      %th
      %th

  %tbody
    - @admin_video_albums.each do |admin_video_album|
      %tr
        %td= admin_video_album.title
        %td= admin_video_album.videos.count
        %td= admin_video_album.views
        %td= link_to 'Посмотреть', admin_video_album
        - if can? :edit, admin_video_album
          %td= link_to 'Редактировать', edit_admin_video_album_path(admin_video_album)
        - if can? :destroy, admin_video_album
          %td= link_to 'Удалить', admin_video_album, method: :delete, data: { confirm: 'Are you sure?' }

%br

app/views/admin/video_albums/new.html.haml
%h1 Создание видеоальбома

= render 'form'

= link_to 'Вернуться к списку видеоальбомов', admin_video_albums_path

app/views/admin/video_albums/show.html.haml
%p
  %b Название:
  = @admin_video_album.title
%p
  %b Главное изображение
  = image_tag @admin_video_album.main_image.small
%p
  %b Описание:
  = @admin_video_album.desc
%p
  %b Кол-во просмотров:
  = @admin_video_album.views

= link_to 'Редактировать', edit_admin_video_album_path(@admin_video_album)
\|
= link_to 'Вернуться к списку видеоальбомов', admin_video_albums_path