config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: "registrations", omniauth_callbacks: 'users/omniauth_callbacks'}

  #########################
  ####
  # Public routes
  ####
  #########################

  root 'public#index'

  get '/articles', to: 'public#articles', as: 'articles'
  get '/news', to: 'public#news', as: 'news'

  get '/photo_albums', to: 'public#photo_albums', as: 'photo_albums'
  get '/video_albums', to: 'public#video_albums', as: 'video_albums'
  get '/album/:id', to: 'public#album', as: 'album'

  get '/finish_registration', to: 'public#finish_registration', as: 'finish_registration'
  # put '/complite_sign_up/:id', to: 'public#complite_sign_up', as: 'complite_sign_up'
  patch '/complite_sign_up/:id', to: 'public#complite_sign_up', as: 'complite_sign_up'

  ###
  # Static pages
  ###

  get '/marriage', to: 'public#marriage', as: 'marriage'
  get '/slav-bazar', to: 'public#slavBazar', as: 'slav-bazar'
  get '/krasnaya-gorka', to: 'public#krasnayaGorka', as: 'krasnaya_gorka'
  get '/rody', to: 'public#rody', as: 'rody'
  get '/vsem_mirom', to: 'public#support', as: 'support'

  #########################
  ####
  # Admin routes
  ####
  #########################

  resources :videos, except: [:index, :show, :new, :edit]
  get 'admin', to: 'admin#dashboard', as: 'admin'
  namespace :admin do
    resources :articles
    resources :users
    resources :video_albums
    resources :photo_albums
    resources :masters
    resources :members
  end

  ###
  # API
  ###

  get '/videoInfo', to: 'videos#getVideoInfo', as: 'getVideoInfo'
  get 'api/get_image_info', to: 'api#get_image_info'
  post 'api/upload_image', to: 'api#upload_image'
  put 'api/change_order', to: 'api#change_order'
  put 'api/change_archive', to: 'api#change_archive', as: 'change_archive'
  put 'api/archive_image', to: 'api#archive_image'
  put 'api/main_image', to: 'api#main_image', as: 'main_image'
  put 'api/bg_image', to: 'api#bg_image', as: 'bg_image'
  put 'api/change_image_info', to: 'api#change_image_info', as: 'change_image_info'
  delete 'api/delete_image', to: 'api#delete_image', as: 'delete_image'
  put 'api/add_member', to: 'api#add_member'
  put 'api/change_payment_method', to: 'api#change_payment_method'
  put 'api/create_payment', to: 'api#create_payment'

  get '/robots.txt' => 'application#robots'
  get 'sitemap.xml', :to => 'sitemap#index', :defaults => { :format => 'xml' }

  ###
  # Posts
  ###

  get '/:id', to: 'public#post', as: 'post'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin/article.rb
class Admin::Article
  include Mongoid::Document
  include Mongoid::Slug
  include Mongoid::Timestamps
  field :title, type: String
  field :content, type: String
  field :desc, type: String
  field :type, type: String
  field :archive, type: Boolean, default: true
  mount_uploader :header, ImageUploader

  belongs_to :author, class_name: "User", optional: true
  slug :title
end

app/controllers/admin/articles_controller.rb
require 'nokogiri'

class Admin::ArticlesController < AdminController
  before_action :set_admin_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /admin/articles
  # GET /admin/articles.json
  def index
    if current_user.role == 'writer'
      @admin_articles = Admin::Article.where(author: current_user)
    else
      @admin_articles = Admin::Article.all
    end
  end

  # GET /admin/articles/1
  # GET /admin/articles/1.json
  def show
  end

  # GET /admin/articles/new
  def new
    @admin_article = Admin::Article.new
  end

  # GET /admin/articles/1/edit
  def edit
  end

  # POST /admin/articles
  # POST /admin/articles.json
  def create
    @admin_article = Admin::Article.new(resource_params)
    respond_to do |format|
      if @admin_article.save
        html = resource_params[:content]
        doc = Nokogiri::HTML(html)
        doc.xpath('@style|.//@style').remove

        doc.search('table').each do |table|
          table['class']="table"
        end

        doc.search('img').each do |img|
          img['class']="img-fluid"
        end

        doc.search('iframe').each do |iframe|
          iframe['class']="embed-responsive-item"
          iframe.parent['class']="embed-responsive embed-responsive-16by9"
        end

        @admin_article.update(content: doc.css('body').inner_html)
        format.html { redirect_to @admin_article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @admin_article }
      else
        format.html { render :new }
        format.json { render json: @admin_article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/articles/1
  # PATCH/PUT /admin/articles/1.json
  def update
    respond_to do |format|
      if @admin_article.update(resource_params)
        html = resource_params[:content]
        doc = Nokogiri::HTML(html)
        doc.xpath('@style|.//@style').remove

        doc.search('table').each do |table|
          table['class']="table"
        end

        doc.search('img').each do |img|
          img['class']="img-fluid"
        end

        # doc.search('figure>').each do |figure|
        #   figure['class']="embed-responsive embed-responsive-16by9"
        # end

        doc.search('iframe').each do |iframe|
          iframe['class']="embed-responsive-item"
          iframe.parent['class']="embed-responsive embed-responsive-16by9"
        end

        @admin_article.update(content: doc.css('body').inner_html)
        format.html { redirect_to @admin_article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_article }
      else
        format.html { render :edit }
        format.json { render json: @admin_article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/articles/1
  # DELETE /admin/articles/1.json
  def destroy
    @admin_article.destroy
    respond_to do |format|
      format.html { redirect_to admin_articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_article
      @admin_article = Admin::Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resource_params
      params.require(:admin_article).permit(:title, :header, :content, :desc, :type, :author_id, :archived)
    end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/views/admin/articles/_form.html.haml
= form_for @admin_article, authenticity_token: true do |f|
  - if @admin_article.errors.any?
    #error_explanation
      %h2= "#{pluralize(@admin_article.errors.count, "error")} prohibited this admin_article from being saved:"
      %ul
        - @admin_article.errors.full_messages.each do |message|
          %li= message
  - if current_user.role == 'author'
    = f.hidden_field :author_id, value: current_user.id
  .field.form-group
    = f.label 'Название'
    = f.text_field :title, class: 'form-control'
  .field.form-group
    = f.label 'Главная картинка'
    = f.file_field :header, class: 'form-control'
  .field.form-group
    = f.label 'Контент'
    = f.text_area :content, class: 'redactor'
  .field.form-group
    = f.label 'Краткое описание'
    = f.text_area :desc, class: 'form-control', rows: 3
  - if current_user.role != 'author'
    .field.form-group
      = f.label 'Автор'
      = select("admin_article", "author_id", User.where(writer: true).map{|u| [u.email, u.id]}, {prompt: 'Выберите пользователя'}, { class: 'form-control' })
  .field.form-group
    = f.label 'Тип поста'
    = select("admin_article", "type", [['Статья','article'],['Новость','news']], {prompt: 'Тип'}, { class: 'form-control' })
  .actions.form-group
    = f.submit 'Сохранить', class: 'btn btn-primary'

app/views/admin/articles/edit.html.haml
%h1 Редактирование поста

= render 'form'

= link_to 'Просмотреть', post_path(@admin_article)
\|
= link_to 'Вернуться к списку постов', admin_articles_path

app/views/admin/articles/index.html.haml
%h1 Посты
= link_to 'Создать пост', new_admin_article_path
%table.table.table-responsive
  %thead
    %tr
      %th Название
      %th Автор
      %th Тип
      %th
      %th
      %th
      %th

  %tbody
    - @admin_articles.each do |admin_article|
      %tr{id: admin_article.id}
        %td= admin_article.title
        %td
          -if admin_article.author
            = link_to admin_user_path(admin_article.author) do
              #{admin_article.author.try(:name)} #{admin_article.author.try(:surname)}
        %td= admin_article.type == 'article' ? 'Статья' : 'Новость'
        - if current_user.accepted || current_user.role == 'moderator' || current_user.role == 'admin'
          %td
            %button.change_archive.btn.btn-link= admin_article.archive ? 'Опубликовать' : 'Добавить в архив'

        %td= link_to 'Просмотреть', admin_article_path(admin_article)
        - if can? :edit, admin_article
          %td= link_to 'Редактировать', edit_admin_article_path(admin_article)
        - if can? :destroy, admin_article
          %td= link_to 'Удалить', admin_article, method: :delete, data: { confirm: 'Уверены? Действие необратимо' }

%br

app/views/admin/articles/new.html.haml
%h1 Новый пост

= render 'form'

= link_to 'Вернуться к списку постов', admin_articles_path

app/views/admin/articles/show.html.haml
.container
  %h1.my-3= @admin_article.title

  .my-3
    = link_to 'Редактировать', edit_admin_article_path(@admin_article)
    \|
    = link_to 'Все статьи', admin_articles_path

  %ul#myTab.nav.nav-tabs{:role => "tablist"}
    %li.nav-item
      %a#content-tab.nav-link.active{"aria-controls" => "content", "aria-selected" => "true", "data-toggle" => "tab", :href => "#content", :role => "tab"} Контент
    %li.nav-item
      %a#desc-tab.nav-link{"aria-controls" => "desc", "aria-selected" => "false", "data-toggle" => "tab", :href => "#desc", :role => "tab"} Описание
  #myTabContent.tab-content.p-3
    #content.tab-pane.fade.show.active{"aria-labelledby" => "home-tab", :role => "tabpanel"}
      .preview-content.p-5
        = raw @admin_article.content
    #desc.tab-pane.fade{"aria-labelledby" => "profile-tab", :role => "tabpanel"}
      %p
        %b Главная картинка
        = image_tag @admin_article.header.small, class: 'img-fluid'
      %p
        %b Автор:
        = link_to admin_user_path(@admin_article.author) do
          #{@admin_article.author.try(:name)} #{@admin_article.author.try(:surname)}
      %p
        %b Тип поста:
        = @admin_article.type