config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: "registrations", omniauth_callbacks: 'users/omniauth_callbacks'}

  #########################
  ####
  # Public routes
  ####
  #########################

  root 'public#index'

  get '/articles', to: 'public#articles', as: 'articles'
  get '/news', to: 'public#news', as: 'news'

  get '/photo_albums', to: 'public#photo_albums', as: 'photo_albums'
  get '/video_albums', to: 'public#video_albums', as: 'video_albums'
  get '/album/:id', to: 'public#album', as: 'album'

  get '/finish_registration', to: 'public#finish_registration', as: 'finish_registration'
  # put '/complite_sign_up/:id', to: 'public#complite_sign_up', as: 'complite_sign_up'
  patch '/complite_sign_up/:id', to: 'public#complite_sign_up', as: 'complite_sign_up'

  ###
  # Static pages
  ###

  get '/marriage', to: 'public#marriage', as: 'marriage'
  get '/slav-bazar', to: 'public#slavBazar', as: 'slav-bazar'
  get '/krasnaya-gorka', to: 'public#krasnayaGorka', as: 'krasnaya_gorka'
  get '/rody', to: 'public#rody', as: 'rody'
  get '/vsem_mirom', to: 'public#support', as: 'support'

  #########################
  ####
  # Admin routes
  ####
  #########################

  resources :videos, except: [:index, :show, :new, :edit]
  get 'admin', to: 'admin#dashboard', as: 'admin'
  namespace :admin do
    resources :articles
    resources :users
    resources :video_albums
    resources :photo_albums
    resources :masters
    resources :members
  end

  ###
  # API
  ###

  get '/videoInfo', to: 'videos#getVideoInfo', as: 'getVideoInfo'
  get 'api/get_image_info', to: 'api#get_image_info'
  post 'api/upload_image', to: 'api#upload_image'
  put 'api/change_order', to: 'api#change_order'
  put 'api/change_archive', to: 'api#change_archive', as: 'change_archive'
  put 'api/archive_image', to: 'api#archive_image'
  put 'api/main_image', to: 'api#main_image', as: 'main_image'
  put 'api/bg_image', to: 'api#bg_image', as: 'bg_image'
  put 'api/change_image_info', to: 'api#change_image_info', as: 'change_image_info'
  delete 'api/delete_image', to: 'api#delete_image', as: 'delete_image'
  put 'api/add_member', to: 'api#add_member'
  put 'api/change_payment_method', to: 'api#change_payment_method'
  put 'api/create_payment', to: 'api#create_payment'

  get '/robots.txt' => 'application#robots'
  get 'sitemap.xml', :to => 'sitemap#index', :defaults => { :format => 'xml' }

  ###
  # Posts
  ###

  get '/:id', to: 'public#post', as: 'post'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin/master.rb
class Admin::Master
  include Mongoid::Document
  # include Mongoid::Slug
  mount_uploader :profile_image, ImageUploader

  field :first_name, type: String
  field :last_name, type: String
  field :patronymic, type: String

  field :about, type: String
  has_many :images, class_name: "Image", :dependent => :destroy
end

app/controllers/admin/masters_controller.rb
class Admin::MastersController < AdminController
  before_action :set_admin_master, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /admin/masters
  # GET /admin/masters.json
  def index
    @admin_masters = Admin::Master.all
  end

  # GET /admin/masters/1
  # GET /admin/masters/1.json
  def show
  end

  # GET /admin/masters/new
  def new
    @admin_master = Admin::Master.new
  end

  # GET /admin/masters/1/edit
  def edit
    @images = @admin_master.images.order_by(:order => 'asc')
  end

  # POST /admin/masters
  # POST /admin/masters.json
  def create
    @admin_master = Admin::Master.new(resource_params)

    respond_to do |format|
      if @admin_master.save
        format.html { redirect_to @admin_master, notice: 'Master was successfully created.' }
        format.json { render :show, status: :created, location: @admin_master }
      else
        format.html { render :new }
        format.json { render json: @admin_master.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/masters/1
  # PATCH/PUT /admin/masters/1.json
  def update
    respond_to do |format|
      if @admin_master.update(resource_params)
        format.html { redirect_to @admin_master, notice: 'Master was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_master }
      else
        format.html { render :edit }
        format.json { render json: @admin_master.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/masters/1
  # DELETE /admin/masters/1.json
  def destroy
    @admin_master.destroy
    respond_to do |format|
      format.html { redirect_to admin_masters_url, notice: 'Master was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_master
      @admin_master = Admin::Master.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resource_params
      params.require(:admin_master).permit(:first_name, :last_name, :patronymic, :about, :profile_image)
    end
end

app/helpers/admin/masters_helper.rb
module Admin::MastersHelper
end

app/views/admin/masters/_form.html.haml
= form_for @admin_master do |f|
  - if @admin_master.errors.any?
    #error_explanation
      %h2= "#{pluralize(@admin_master.errors.count, "error")} prohibited this admin_master from being saved:"
      %ul
        - @admin_master.errors.full_messages.each do |message|
          %li= message

  .field.form-group
    = f.label 'Фамилия'
    = f.text_field :last_name, class: 'form-control'
  .field.form-group
    = f.label 'Имя'
    = f.text_field :first_name, class: 'form-control'
  .field.form-group
    = f.label 'Отчество'
    = f.text_field :patronymic, class: 'form-control'
  %hr
  .field.form-group
    = f.label 'Фото мастера'
    = f.file_field :profile_image, class: 'form-control'
  .field.form-group
    = f.label 'О Мастере'
    = f.text_area :about, class: 'redactor'
  .actions.form-group
    = f.submit 'Сохранить', class: 'btn btn-primary'

app/views/admin/masters/edit.html.haml
%h1 Редактирование мастера

= render 'form'

%hr
.row.mb-4
  .col-2.col-form-label
    Загрузить изображения
  .col-10
    = render 'admin/dropzone', master: @admin_master.id
#sortableGrid.row
  -@images.each do |image|
    .col-3.image{id: image.id, class: (image.archive ? 'archived' : '')}
      .card{class: (image.main_image ? 'border-primary' : '')}
        =image_tag image.image, class: 'card-img-top'
        .card-body
          -# %button.btn.btn-link.editInfo{"data-target" => "#editInfoModal", "data-toggle" => "modal", :type => "button"} Редактировать
          -# %button.btn.btn-link.setMainImage{class: (image.main_image ? 'd-none' : '')} Сделать главной
          -# - if image.archive
          -#   %button.btn.btn-link.archiveImage Достать из архива
          -# - else
          -#   %button.btn.btn-link.archiveImage Добавить в архив
          %button.btn.btn-link.deleteImage Удалить

app/views/admin/masters/index.html.haml
%h1 Список Мастеров

= link_to 'Создать мастера', new_admin_master_path
%table.table.table-responsive
  %thead
    %tr
      %th Фото
      %th ФИО
      %th
      %th
      %th

  %tbody
    - @admin_masters.each do |admin_master|
      %tr
        %td= image_tag admin_master.profile_image.thumb, class: 'img-fluid', width: 50
        %td= admin_master.last_name + ' ' + admin_master.first_name + ' ' + admin_master.patronymic
        %td= link_to 'Посмотреть', admin_master
        %td= link_to 'Редактировать', edit_admin_master_path(admin_master)
        %td= link_to 'Удалить', admin_master, method: :delete, data: { confirm: 'Are you sure?' }

app/views/admin/masters/new.html.haml
%h1 Создание мастера

= render 'form'

= link_to 'Back', admin_masters_path

app/views/admin/masters/show.html.haml
= image_tag @admin_master.profile_image.thumb, class: 'img-fluid'

%p
  %b ФИО:
  = @admin_master.last_name + ' ' + @admin_master.first_name + ' ' + @admin_master.patronymic
%p
  %b О Мастере:
  = raw @admin_master.about

= link_to 'Редактировать', edit_admin_master_path(@admin_master)
\|
= link_to 'Назад', admin_masters_path