config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: "registrations", omniauth_callbacks: 'users/omniauth_callbacks'}

  #########################
  ####
  # Public routes
  ####
  #########################

  root 'public#index'

  get '/articles', to: 'public#articles', as: 'articles'
  get '/news', to: 'public#news', as: 'news'

  get '/photo_albums', to: 'public#photo_albums', as: 'photo_albums'
  get '/video_albums', to: 'public#video_albums', as: 'video_albums'
  get '/album/:id', to: 'public#album', as: 'album'

  get '/finish_registration', to: 'public#finish_registration', as: 'finish_registration'
  # put '/complite_sign_up/:id', to: 'public#complite_sign_up', as: 'complite_sign_up'
  patch '/complite_sign_up/:id', to: 'public#complite_sign_up', as: 'complite_sign_up'

  ###
  # Static pages
  ###

  get '/marriage', to: 'public#marriage', as: 'marriage'
  get '/slav-bazar', to: 'public#slavBazar', as: 'slav-bazar'
  get '/krasnaya-gorka', to: 'public#krasnayaGorka', as: 'krasnaya_gorka'
  get '/rody', to: 'public#rody', as: 'rody'
  get '/vsem_mirom', to: 'public#support', as: 'support'

  #########################
  ####
  # Admin routes
  ####
  #########################

  resources :videos, except: [:index, :show, :new, :edit]
  get 'admin', to: 'admin#dashboard', as: 'admin'
  namespace :admin do
    resources :articles
    resources :users
    resources :video_albums
    resources :photo_albums
    resources :masters
    resources :members
  end

  ###
  # API
  ###

  get '/videoInfo', to: 'videos#getVideoInfo', as: 'getVideoInfo'
  get 'api/get_image_info', to: 'api#get_image_info'
  post 'api/upload_image', to: 'api#upload_image'
  put 'api/change_order', to: 'api#change_order'
  put 'api/change_archive', to: 'api#change_archive', as: 'change_archive'
  put 'api/archive_image', to: 'api#archive_image'
  put 'api/main_image', to: 'api#main_image', as: 'main_image'
  put 'api/bg_image', to: 'api#bg_image', as: 'bg_image'
  put 'api/change_image_info', to: 'api#change_image_info', as: 'change_image_info'
  delete 'api/delete_image', to: 'api#delete_image', as: 'delete_image'
  put 'api/add_member', to: 'api#add_member'
  put 'api/change_payment_method', to: 'api#change_payment_method'
  put 'api/create_payment', to: 'api#create_payment'

  get '/robots.txt' => 'application#robots'
  get 'sitemap.xml', :to => 'sitemap#index', :defaults => { :format => 'xml' }

  ###
  # Posts
  ###

  get '/:id', to: 'public#post', as: 'post'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :trackable, :validatable

  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable

  devise :omniauthable, omniauth_providers: %i[vkontakte]

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time



  field :name, type: String
  field :surname, type: String

  field :role, type: String, default: "user"
  field :accepted, type: Boolean, default: false
  field :writer, type: Boolean, default: false
  field :photographer, type: Boolean, default: false


  has_many :articles, class_name: "Admin::Article"
  has_many :photo_albums, class_name: "Admin::PhotoAlbum"
  has_many :video_albums, class_name: "Admin::VideoAlbum"


  field :provider
  field :uid
  field :fakeEmail, type: Boolean, default: false

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        email:    User.dummy_email(auth),
        password: Devise.friendly_token[0, 20],
        fakeEmail: true
      )
    end

    user
  end

  def will_save_change_to_email?
    false
  end

  # def self.new_with_session(params, session)
  #  super.tap do |user|
  #    if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
  #      user.email = data["email"] if user.email.blank?
  #    end
  #  end
  # end

  private

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@fam-academy.ru"
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_action :set_admin_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /admin/users
  # GET /admin/users.json
  def index
    @admin_users = User.all
  end

  # GET /admin/users/1
  # GET /admin/users/1.json
  def show
  end

  # GET /admin/users/new
  def new
    @admin_user = User.new
  end

  # GET /admin/users/1/edit
  def edit
  end

  # POST /admin/users
  # POST /admin/users.json
  def create
    @admin_user = User.new(admin_user_params)
    if admin_user_params.has_key?(:role) && ((current_user.role == 'moderator') && (admin_user_params[:role] == 'admin'))
      respond_to do |format|
        flash[:error] = 'Вы не имеете права создать пользователя с большим уровнем привелегий'
        format.html { render :new }
      end
    else
      respond_to do |format|
        if @admin_user.save
          format.html { redirect_to admin_user_path(@admin_user), notice: 'User was successfully created.' }
          format.json { render :show, status: :created, location: @admin_user }
        else
          format.html { render :new }
          format.json { render json: @admin_user.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /admin/users/1
  # PATCH/PUT /admin/users/1.json
  def update
    if admin_user_params.has_key?(:role) && ((current_user.id == @admin_user.id) && (current_user.role != 'admin') && (current_user.role != admin_user_params[:role])) || ((current_user.role == 'moderator') && (admin_user_params[:role] == 'admin'))
      respond_to do |format|
        flash[:error] = 'Вы не имеете права редактировать уровень своих привелегий'
        format.html { render :new }
      end
    else
      respond_to do |format|
        if @admin_user.update(admin_user_params)
          format.html { redirect_to admin_user_path(@admin_user), notice: 'User was successfully updated.' }
          format.json { render :show, status: :ok, location: @admin_user }
        else
          format.html { render :edit }
          format.json { render json: @admin_user.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /admin/users/1
  # DELETE /admin/users/1.json
  def destroy
    @admin_user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_user
      @admin_user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_user_params
      params.require(:user).permit(:name, :surname, :role, :writer, :photographer, :email)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def vkontakte
    callback_from :vkontakte
  end

  private

  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => provider.capitalize) if is_navigational_format?
    else
      session["devise.#{provider}_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.haml
= form_for @admin_user, url: admin_user_path(@admin_user), html: { multipart: true } do |f|
  - if @admin_user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@admin_user.errors.count, "error")} prohibited this admin_user from being saved:"
      %ul
        - @admin_user.errors.full_messages.each do |message|
          %li= message

  .field.form-group
    = f.label 'Имя'
    = f.text_field :name, class: 'form-control'
  .field.form-group
    = f.label 'Фамилия'
    = f.text_field :surname, class: 'form-control'
  .field.form-group
    = f.label 'Email'
    = f.text_field :email, class: 'form-control'

  - if ((current_user.id != @admin_user.id) && (current_user.role == 'moderator')) || (current_user.role == 'admin')
    .field.form-group
      = f.label 'Роль'
      - if current_user.role == 'moderator'
        = select("user", "role", options_for_select([ "user", "author", "moderator"], @admin_user.role), {},{class: 'form-control'})
      - if current_user.role == 'admin'
        = select("user", "role", options_for_select([ "user", "author", "moderator", "admin"], @admin_user.role), {},{class: 'form-control'})
    .field.form-group
      = f.label 'Автор статей'
      = f.check_box :writer
    .field.form-group
      = f.label 'Фотограф'
      = f.check_box :photographer

  .actions.form-group
    = f.submit 'Сохранить', class: 'btn btn-primary'

app/views/admin/users/edit.html.haml
%h1 Редактирование пользователя

= render 'form'

= link_to 'Просмотреть', admin_user_path(@admin_user)
\|
= link_to 'Вернуться к списку пользователей', admin_users_path

app/views/admin/users/index.html.haml
%h1 Список пользователей

%table.table.table-responsive
  %thead
    %tr
      %th Имя
      %th Email
      %th Роль
      %th Вид активности
      %th
      %th
      %th

  %tbody
    - @admin_users.each do |admin_user|
      %tr
        %td
          = admin_user.name
          = admin_user.surname
        %td= admin_user.email
        %td= admin_user.role
        %td
          = admin_user.writer && admin_user.photographer ? ' Автор статей; Фотограф' : ''
          = admin_user.writer && !(admin_user.photographer) ? ' Автор статей' : ''
          = !(admin_user.writer) && admin_user.photographer ? ' Фотограф' : ''
        %td= link_to 'Просмотреть', admin_user_path(admin_user)
        - if can? :edit, admin_user
          %td= link_to 'Редактировать', edit_admin_user_path(admin_user)
        - if can? :destroy, admin_user
          %td= link_to 'Удалить', admin_user_path(admin_user), method: :delete, data: { confirm: 'Уверены? Действие необратимо' }

%br

-# = link_to 'Создать пользователя', new_admin_user_path

app/views/admin/users/new.html.haml
%h1 Новый пользователь

= form_for @admin_user, url: admin_users_path, html: { multipart: true } do |f|
  - if @admin_user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@admin_user.errors.count, "error")} prohibited this admin_user from being saved:"
      %ul
        - @admin_user.errors.full_messages.each do |message|
          %li= message

  .actions.form-group
    = f.submit 'Сохранить'

= link_to 'Вернуться к списку пользователей', admin_users_path

app/views/admin/users/show.html.haml
%p
  %b Email:
  = @admin_user.email
%p
  %b Имя:
  = @admin_user.name
%p
  %b Фамилия:
  = @admin_user.surname
%p
  %b Роль:
  = @admin_user.role

= link_to 'Редактировать', edit_admin_user_path(@admin_user)
\|
= link_to 'все пользователи', admin_users_path